=== vladkasyan/xml-enrollment/kasianvladyslav.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Transakcje">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Transakcja" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Lp" type="xs:integer"/>
              <xs:element name="Nazwa" type="xs:string"/>
              <xs:element name="Kwota" type="xs:string"/>
              <xs:element name="Waluta">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="PLN"/>
                    <xs:enumeration value="EUR"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Wykonawca" type="xs:string" nillable="true"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== vladkasyan/xml-enrollment/kasianvladyslav.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="kasianvladyslav.xslt"?>
<Transakcje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="kasianvladyslav.xsd">
  <Transakcja>
    <Lp>1</Lp>
    <Nazwa>wpłata</Nazwa>
    <Kwota>1000,50</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca>Adam A.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>2</Lp>
    <Nazwa>odsetki</Nazwa>
    <Kwota>20,00</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca xsi:nil="true"/>
  </Transakcja>
  <Transakcja>
    <Lp>3</Lp>
    <Nazwa>wpłata</Nazwa>
    <Kwota>250,00</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca>Jan J.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>4</Lp>
    <Nazwa>przelew</Nazwa>
    <Kwota>1234,50</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Jan J.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>5</Lp>
    <Nazwa>przelew</Nazwa>
    <Kwota>2222,22</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Ewa B.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>6</Lp>
    <Nazwa>przelew</Nazwa>
    <Kwota>444,00</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Adam A.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>7</Lp>
    <Nazwa>korekta</Nazwa>
    <Kwota>20,50</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca>Adam A.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>8</Lp>
    <Nazwa>odsetki</Nazwa>
    <Kwota>10,00</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca xsi:nil="true"/>
  </Transakcja>
  <Transakcja>
    <Lp>9</Lp>
    <Nazwa>wpłata</Nazwa>
    <Kwota>2250,50</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Jan J.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>10</Lp>
    <Nazwa>przelew</Nazwa>
    <Kwota>4567,00</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca>Ewa B.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>11</Lp>
    <Nazwa>wpłata</Nazwa>
    <Kwota>500,00</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca>Adam A.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>12</Lp>
    <Nazwa>wpłata</Nazwa>
    <Kwota>15000,00</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Jan J.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>13</Lp>
    <Nazwa>przelew</Nazwa>
    <Kwota>100,00</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca>Ewa B.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>14</Lp>
    <Nazwa>korekta</Nazwa>
    <Kwota>40,50</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Adam A.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>15</Lp>
    <Nazwa>wpłata</Nazwa>
    <Kwota>900,00</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Jan J.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>16</Lp>
    <Nazwa>wpłata</Nazwa>
    <Kwota>100,00</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Jan J.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>17</Lp>
    <Nazwa>przelew</Nazwa>
    <Kwota>100,00</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca>Ewa B.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>18</Lp>
    <Nazwa>przelew</Nazwa>
    <Kwota>100,00</Kwota>
    <Waluta>PLN</Waluta>
    <Wykonawca>Ewa B.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>19</Lp>
    <Nazwa>korekta</Nazwa>
    <Kwota>40,50</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Adam A.</Wykonawca>
  </Transakcja>
  <Transakcja>
    <Lp>20</Lp>
    <Nazwa>wpłata</Nazwa>
    <Kwota>900,00</Kwota>
    <Waluta>EUR</Waluta>
    <Wykonawca>Jan J.</Wykonawca>
  </Transakcja>
</Transakcje>
